title: Other HTTP errors
naviTitle: Other HTTP errors
navigation.excerpt: Information about less common HTTP errors
lead: Other HTTP errors you may encounter when working with web applications and APIs that are less common than the standard ones like 404 or 500.